baseURL = ""
relativeURLs = true
defaultContentLanguage = 'en'
languageCode = "en-en"
title = "nearbyevcharging - Soak up the sun â˜€ï¸ğŸš˜ - Very easily."

[site]
  [params]
  description = "nearbyevcharging ermÃ¶glicht es Elektrovehicles mit mÃ¶glichst viel selbsterzeugten Solarstrom zu laden."

[minify]
  disableSVG = true
  disableHTML = true

[security]
  [security.funcs]
    getenv = ["SLACK_INVITE_URL"]